title: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My portfolio showcasing my projects and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your_username
github_username: your_username
theme: hyde

plugins:
  - jekyll-feed
